### ISSUE TITLE
Use `js-tokens` to reduce the size of this dependency

### ISSUE THREAD

**Issue by sheremet-va** [antfu/strip-literal#5]
### Clear and concise description of the problem

This package uses `acorn` to parse JS code which is a bit large for the use case.

### Suggested solution

I propose using [`js-tokens`](https://github.com/lydell/js-tokens) instead of acorn to reduce the size of this package. This package is used in Vite and Vitest that both had `acorn` in dependencies through `rollup`, but `rollup` stopped using `acorn` in the latest major version.

The package itself is much more lightweight, but it relies on a series of regexp manipulations. Still, as far as I understand, it correctly finds commends and multicomments.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds interesting, PR welcome if you want to work on it 👀
